<?php

/**
 * A helper file for IDE autocompletion.
 *
 * This file is automatically generated. DO NOT EDIT DIRECTLY.
 */

namespace {
    class Cache extends \Ody\Foundation\Facades\Cache
    {
    }
}


// Global Facades
namespace {
    /**
     * @method static mixed get(string $key, mixed $default = null)
     * @method static bool set(string $key, mixed $value, null|int|\DateInterval $ttl = null)
     * @method static bool delete(string $key)
     * @method static bool clear()
     * @method static iterable getMultiple(iterable $keys, mixed $default = null)
     * @method static bool setMultiple(iterable $values, null|int|\DateInterval $ttl = null)
     * @method static bool deleteMultiple(iterable $keys)
     * @method static bool has(string $key)
     * @method static \Ody\Foundation\Cache\TaggedCache tags(array|string $tags)
     * @method static \Psr\Cache\CacheItemInterface getItem(string $key)
     * @method static array getItems(array $keys = [])
     * @method static bool save(\Psr\Cache\CacheItemInterface $item)
     * @method static bool saveDeferred(\Psr\Cache\CacheItemInterface $item)
     * @method static bool commit()
     */
    class Cache extends \Ody\Foundation\Facades\Cache
    {
    }

}

// End of IDE helper