name: PHPunit Mysql 8.0, Postgres 14

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.4' ]

    name: PHPunit - PHP ${{ matrix.php }}

    services:
      mysql:
        image: bitnami/mysql:8.0.27
        env:
          MYSQL_DATABASE: ody
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
          MYSQL_CHARACTER_SET: utf8mb4
          MYSQL_COLLATE: utf8mb4_general_ci
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --no-progress --no-interaction && composer require "symfony/console:<7.0.0"

      - name: PHPunit
        run: vendor/bin/phpunit
        env:
          ODY_MYSQL_HOST: 127.0.0.1
          ODY_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          ODY_MYSQL_PASSWORD: postgres
          ODY_PGSQL_PORT: ${{ job.services.postgres.ports[5432] }}
          ODY_PGSQL_PASSWORD: postgres
