name: Subtree Split

on:
  push:
    branches:
      - master
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { name: "auth", path: "packages/auth" }
          - { name: "container", path: "packages/container" }
          - { name: "database", path: "packages/database" }
          - { name: "foundation", path: "packages/foundation" }
          - { name: "influxdb", path: "packages/influxdb" }
          - { name: "logger", path: "packages/logger" }
          - { name: "process", path: "packages/process" }
          - { name: "scheduler", path: "packages/scheduler" }
          - { name: "server", path: "packages/server" }
          - { name: "support", path: "packages/support" }
          - { name: "swoole", path: "packages/swoole" }
          - { name: "task", path: "packages/task" }
          - { name: "websocket", path: "packages/websocket" }
          - { name: "connection-pool", path: "packages/connection-pool" }
          - { name: "amqp", path: "packages/amqp" }

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Split ${{ matrix.package.name }}
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: ${{ matrix.package.path }}
          repository_organization: ody-dev
          repository_name: ${{ matrix.package.name }}
          user_name: "Ilyas Deckers"
          user_email: "ilyas@ody.dev"
          branch: ${{ github.ref_name }}
