name: Subtree Split

on:
  push:
    branches:
      - master
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { name: "container", path: "packages/container" }

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Split ${{ matrix.package.name }}
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: ${{ matrix.package.path }}
          repository_organization: ody-dev
          repository_name: ${{ matrix.package.name }}
          user_name: "Ilyas Deckers"
          user_email: "ilyas@ody.dev"
          branch: ${{ github.ref_name }}